"""Add metadata sync tables

Revision ID: 3a2f7fe9b5c2
Revises: 9722860d4fd4
Create Date: 2026-02-05 13:01:18.538690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2f7fe9b5c2'
down_revision: Union[str, Sequence[str], None] = '9722860d4fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create metadata_sync_logs table
    op.create_table(
        'metadata_sync_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('sync_type', sa.String(length=20), nullable=True),
        sa.Column('git_commit_hash', sa.String(length=40), nullable=True),
        sa.Column('tests_discovered', sa.Integer(), nullable=True),
        sa.Column('tests_added', sa.Integer(), nullable=True),
        sa.Column('tests_updated', sa.Integer(), nullable=True),
        sa.Column('tests_removed', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_details', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_started', 'metadata_sync_logs', ['started_at'], unique=False)
    op.create_index('idx_sync_status', 'metadata_sync_logs', ['status'], unique=False)

    # Create testcase_metadata_changes table
    op.create_table(
        'testcase_metadata_changes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sync_log_id', sa.Integer(), nullable=True),
        sa.Column('testcase_name', sa.String(length=200), nullable=False),
        sa.Column('change_type', sa.String(length=20), nullable=False),
        sa.Column('old_values', sa.Text(), nullable=True),
        sa.Column('new_values', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['sync_log_id'], ['metadata_sync_logs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_sync_log', 'testcase_metadata_changes', ['sync_log_id'], unique=False)
    op.create_index('idx_change_testcase', 'testcase_metadata_changes', ['testcase_name'], unique=False)

    op.alter_column('jobs', 'jenkins_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.drop_index(op.f('idx_parent_job'), table_name='jobs')
    op.drop_index(op.f('idx_parent_job_id'), table_name='jobs')
    op.drop_index(op.f('idx_parent_version'), table_name='jobs')
    op.alter_column('releases', 'jenkins_job_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('test_results', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('idx_job_priority'), table_name='test_results')
    op.drop_index(op.f('idx_job_topology_metadata'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_topology'), table_name='test_results')
    op.create_index('idx_job_topology', 'test_results', ['job_id', 'jenkins_topology'], unique=False)
    op.create_index(op.f('ix_test_results_jenkins_topology'), 'test_results', ['jenkins_topology'], unique=False)
    op.create_index(op.f('ix_test_results_priority'), 'test_results', ['priority'], unique=False)
    op.create_index(op.f('ix_test_results_topology_metadata'), 'test_results', ['topology_metadata'], unique=False)
    op.drop_index(op.f('ix_testcase_metadata_priority'), table_name='testcase_metadata')
    op.drop_index(op.f('ix_testcase_metadata_test_case_id'), table_name='testcase_metadata')
    op.drop_index(op.f('ix_testcase_metadata_testcase_name'), table_name='testcase_metadata')
    op.drop_index(op.f('ix_testcase_metadata_testrail_id'), table_name='testcase_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop testcase_metadata_changes table
    op.drop_index('idx_change_testcase', table_name='testcase_metadata_changes')
    op.drop_index('idx_change_sync_log', table_name='testcase_metadata_changes')
    op.drop_table('testcase_metadata_changes')

    # Drop metadata_sync_logs table
    op.drop_index('idx_sync_status', table_name='metadata_sync_logs')
    op.drop_index('idx_sync_started', table_name='metadata_sync_logs')
    op.drop_table('metadata_sync_logs')

    op.create_index(op.f('ix_testcase_metadata_testrail_id'), 'testcase_metadata', ['testrail_id'], unique=False)
    op.create_index(op.f('ix_testcase_metadata_testcase_name'), 'testcase_metadata', ['testcase_name'], unique=1)
    op.create_index(op.f('ix_testcase_metadata_test_case_id'), 'testcase_metadata', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_testcase_metadata_priority'), 'testcase_metadata', ['priority'], unique=False)
    op.drop_index(op.f('ix_test_results_topology_metadata'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_priority'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_jenkins_topology'), table_name='test_results')
    op.drop_index('idx_job_topology', table_name='test_results')
    op.create_index(op.f('ix_test_results_topology'), 'test_results', ['jenkins_topology'], unique=False)
    op.create_index(op.f('idx_job_topology_metadata'), 'test_results', ['job_id', 'topology_metadata'], unique=False)
    op.create_index(op.f('idx_job_priority'), 'test_results', ['job_id', 'priority'], unique=False)
    op.alter_column('test_results', 'file_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('releases', 'jenkins_job_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.create_index(op.f('idx_parent_version'), 'jobs', ['parent_job_id', 'version'], unique=False)
    op.create_index(op.f('idx_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('idx_parent_job'), 'jobs', ['parent_job_id'], unique=False)
    op.alter_column('jobs', 'jenkins_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
