"""Initial schema: 6 tables for test tracking

Revision ID: d629f0307876
Revises: 
Create Date: 2026-01-16 16:57:08.372568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd629f0307876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('releases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('jenkins_job_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_name'), 'releases', ['name'], unique=True)
    op.create_table('jenkins_polling_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('modules_downloaded', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_polling_started', 'jenkins_polling_logs', ['started_at'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_release_module', 'modules', ['release_id', 'name'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('jenkins_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_created', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_module_job', 'jobs', ['module_id', 'job_id'], unique=True)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'SKIPPED', 'ERROR', name='teststatusenum'), nullable=False),
    sa.Column('setup_ip', sa.String(length=50), nullable=True),
    sa.Column('topology', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('was_rerun', sa.Boolean(), nullable=True),
    sa.Column('rerun_still_failed', sa.Boolean(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status', 'test_results', ['job_id', 'status'], unique=False)
    op.create_index('idx_test_key', 'test_results', ['file_path', 'class_name', 'test_name'], unique=False)
    op.create_index('idx_topology', 'test_results', ['topology'], unique=False)
    op.create_index(op.f('ix_test_results_status'), 'test_results', ['status'], unique=False)
    op.create_index(op.f('ix_test_results_topology'), 'test_results', ['topology'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_topology'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_status'), table_name='test_results')
    op.drop_index('idx_topology', table_name='test_results')
    op.drop_index('idx_test_key', table_name='test_results')
    op.drop_index('idx_job_status', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('idx_module_job', table_name='jobs')
    op.drop_index('idx_job_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_release_module', table_name='modules')
    op.drop_table('modules')
    op.drop_index('idx_polling_started', table_name='jenkins_polling_logs')
    op.drop_table('jenkins_polling_logs')
    op.drop_index(op.f('ix_releases_name'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
